name: Scrape latest data
on:
  push:
  workflow_dispatch:
  # Set schedule if you want to run this periodically.
  # schedule:
  #  - cron: '0 12 * * *'

permissions:
  contents: write

jobs:
  scrape:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run npx tsimp index.ts
        run: npx tsimp index.ts
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
        env:
          TZ: Asia/Tokyo
